ColorColumn: 'yellow2 shadow'
Conceal: ''
# no, you can't change the cursor color in vim
# instead set it to #858d97 on your terminal
Cursor: '- shadow_highlight'
iCursor: '- shadow_highlight'
CursorIM: 'background orange3'

CursorColumn: '- background_accent'
CursorLine: '- current_row'
CursorLineNr: 'gold2 shadow b'

Directory: 'yellow1 -'

DiffAdd: '- green4'
DiffChange: '- blue4'
DiffDelete: 'text red3'
DiffText: 'grey1 - r'

ErrorMsg: 'red2 -'

VertSplit: 'background_accent background_accent'

Folded: 'grey2 darker'
FoldColumn: 'grey2 darker'

SignColumn: 'orange3 background_accent'
IncSearch: 'background highlighted'

LineNr: 'grey3 background_accent'

MatchParen: '- shadow_highlight b'

ModeMsg: 'orange3'
MoreMsg: 'orange3'

NonText: 'grey3 -'

Normal: 'text background'

PMenu: 'text shadow'
PMenuSel: 'background gold2'
PmenuSbar: 'gold1 -'
PmenuThumb: 'gold2 gold2'
Question: 'orange3 -'
Search: 'grey1 - ub'
SpecialKey: 'grey3 -'
SpellBad: 'gold1 -'
SpellLocal: 'gold1'
SpellCap: 'background gold2'
SpellRare: 'blue2'
StatusLine: 'darker grey2 b'
StatusLineNC: 'grey1 -'
TabLine: 'grey1 -'
TabLineFill: '- grey3'
TabLineSel: 'green1 - b'
Title: 'blue1 - b'
Visual: '- selection_background'
VisualNOS: '- selection_background'
WarningMsg: 'orange1 -'
WildMenu: 'background green1 b'
Comment: 'comment'

Constant: 'purple1 -'

String: 'string -' # Constant
Character: 'green1 -' # Constant
Boolean: 'red1 -' # Constant
Number: 'red1 -' # Constant
Float: 'red1 -' # Constant

Identifier: 'blue3 -'

Function: 'function -' # Identifier

Statement: 'blue1 -'
Conditional: 'blue1 -' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'blue1 -' # Statement
Keyword: 'blue4' # Statement
Exception: 'red2 -' # Statement
PreProc: 'blue1 -' # Reserved words #x
Include: 'blue1 -' # PreProc
Define: 'define -' # PreProc
Macro: 'blue1 -' # PreProc
PreCondit: 'blue1 -' # PreProc
Type: 'type -' #x
StorageClass: '' # Type
Structure: 'yellow2 -' # Type
Typedef: 'yellow2 -' # Type
Special: 'blue4 -'
SpecialChar: 'green1 -' # Special
Tag: 'purple4 -' # Special
Delimiter: 'green2 -' # Special
SpecialComment: 'grey1 -' # Special
Debug: '' # Special
Underlined: '- - u'
Ignore: ''
Error: 'id - b'
Todo: 'orange2 - b'
