ColorColumn: 'yellow2 shadow'
Conceal: ''
Cursor: '- green1'
iCursor: '- gold1'
CursorIM: '- gold1'
CursorColumn: '- bg_accent'
CursorLine: 'text shadow'
CursorLineNr: 'gold2 shadow b'
Directory: 'yellow1 -'
DiffAdd: '- green4'
DiffChange: '- blue4'
DiffDelete: 'text red3'
DiffText: 'grey1 - r'
ErrorMsg: 'red2 -'
VertSplit: 'bg_accent bg_accent'
Folded: 'grey2 darker'
FoldColumn: 'grey2 darker'
SignColumn: 'orange3 bg_accent'
IncSearch: 'bg highlighted'
LineNr: 'grey3 bg_accent'
MatchParen: 'red2 - b'
ModeMsg: 'orange3'
MoreMsg: 'orange3'
NonText: 'grey3 -'
Normal: 'text bg'
PMenu: 'text shadow'
PMenuSel: 'bg gold2'
PmenuSbar: 'gold1 -'
PmenuThumb: 'gold2 gold2'
Question: 'orange3 -'
Search: 'grey1 - ub'
SpecialKey: 'grey3 -'
SpellBad: 'gold1 -'
SpellLocal: 'gold1'
SpellCap: 'bg gold2'
SpellRare: 'blue2'
StatusLine: 'darker grey2 b'
StatusLineNC: 'grey1 -'
TabLine: 'grey1 -'
TabLineFill: '- grey3'
TabLineSel: 'green1 - b'
Title: 'blue1 - b'
Visual: 'darkest text_contrast'
VisualNOS: 'darkest text_contrast'
WarningMsg: 'orange1 -'
WildMenu: 'bg green1 b'
Comment: 'comment'

Constant: 'purple1 -'

String: 'green1 -' # Constant
Character: 'green1 -' # Constant
Boolean: 'red1 -' # Constant
Number: 'red1 -' # Constant
Float: 'red1 -' # Constant

Identifier: 'blue3 -'

Function: 'orange2 -' # Identifier
Statement: 'blue1 -'
Conditional: 'blue1 -' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'blue1 -' # Statement
Keyword: 'blue4' # Statement
Exception: 'red2 -' # Statement
PreProc: 'blue1 -' # Reserved words #x
Include: 'blue1 -' # PreProc
Define: 'blue1 -' # PreProc
Macro: 'blue1 -' # PreProc
PreCondit: 'blue1 -' # PreProc
Type: 'yellow2 -' #x
StorageClass: '' # Type
Structure: 'yellow2 -' # Type
Typedef: 'yellow2 -' # Type
Special: 'blue4 -'
SpecialChar: 'green1 -' # Special
Tag: 'purple4 -' # Special
Delimiter: 'green2 -' # Special
SpecialComment: 'grey1 -' # Special
Debug: '' # Special
Underlined: '- - u'
Ignore: ''
Error: 'red3 - b'
Todo: 'orange2 - b'
